# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: true
reviews:
  profile: 'chill'
  high_level_summary: true
  auto_review:
    enabled: true
    labels: ['!wip']
    base_branches: ['gt-*']
  pre_merge_checks:
    docstrings:
      mode: 'warning'
      threshold: 80
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
