reviews:
  review_status: true
  allow_non_default_base: true
  base_branch_allowlist:
    - "gt-v0.3/**"
checks:
  docstring_coverage_threshold: 80
  markdown_lint: true
style:
  review_profile: CHILL
